=== rubencarneiro/sagetea.github.io/installer-configs/v3/device.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/device.schema.yml","title":"Device","description":"Device configuration for the UBports Installer","type":"object","properties":{"name":{"title":"Name","type":"string","description":"The human-readable name under which the device was marketed. This includes the name of the manufacturer if it makes sense. I.e. you would not refer to the 'Oneplus One' as 'One', but you would not call the 'iPhone 9' 'Apple iPhone 9'. Use common sense."},"codename":{"title":"Codename","type":"string","description":"A short codename that is used internally to identify the device. This (with the extension '.yml') should also be the filename. If there are multiple codenames in use for the exact same device, only create a single one with the most prominent one and add the correct aliases to aliases.json."},"formfactor":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/formfactor.schema.yml","title":"Formfactor","type":"string","description":"What kind of device is it?","enum":["computer","laptop","phone","tablet","watch"]},"aliases":{"title":"Aliases","type":"array","description":"Alternative codenames this device might be identified as.","uniqueItems":true,"items":{"type":"string"}},"doppelgangers":{"title":"Doppelgangers","type":"array","description":"Codenames of devices this device should not be confused with.","uniqueItems":true,"items":{"type":"string"}},"user_actions":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/user_actions.schema.yml","title":"User actions","type":"object","description":"Object that contains instructions for the user for later reference.","patternProperties":{"\\w":{"title":"User action","type":"object","description":"Instruction that can be referenced and presented to the user. Eg key combinations to reboot to recovery or bootloader.","properties":{"title":{"title":"Title","type":"string","description":"Identifier of the step. Eg. 'Enable USB-debugging'"},"description":{"title":"Description","type":"string","description":"Short description of the step. For simple tasks, the full instructions can be put here."},"image":{"title":"Image","type":"string","description":"String referring to a picture in the installer.","enum":["phone_power_up","phone_power_down"]},"button":{"title":"Button","type":"boolean","description":"Specify whether there should be a done-button displayed."},"link":{"title":"Link","type":"string","description":"A link to a more extensive tutorial."}},"required":["title","description"]}},"additionalProperties":false},"handlers":{"title":"Handlers","type":"object","description":"Steps to run to handle specific known errors","properties":{"bootloader_locked":{"title":"Handle a bootloader locked error","$ref":"#/properties/operating_systems/items/properties/steps/items"}},"additionalProperties":false},"unlock":{"title":"Unlock actions","type":"array","description":"An array of strings referring to user_actions defined above that are needed to unlock the device. This might include simple things like enabling adb access or bigger steps like using a leaked oem tool to flash highly questionable images that unlock the bootloader. Whatever is needed to make installations possible.","uniqueItems":true,"items":{"type":"string"}},"operating_systems":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/operating_systems.schema.yml","title":"Operating systems","type":"array","description":"An array of objects describing operating systems available for installation.","uniqueItems":true,"items":{"title":"Operating system","type":"object","description":"An operating system available for installation","properties":{"name":{"title":"OS name","type":"string","description":"Human-readable name of the operating system."},"options":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/options.schema.yml","title":"Options","type":"array","description":"Options for the installation.","items":{"title":"Option","type":"object","description":"Option for the installation.","properties":{"var":{"type":"string","description":"Variable the setting will be stored in."},"name":{"type":"string","description":"Human-readable identifier of the setting."},"tooltip":{"type":"string","description":"A very short help text describing the setting."},"link":{"type":"string","description":"A link to the docs describing the setting."},"type":{"type":"string","description":"Describes what values are accepted by the setting and how they are provided.","enum":["checkbox","input","select"]},"remote_values":{"title":"Remote values","type":"object","description":"If the values can be generated from a remote source like the systemimage api, this provides the required information for that.","additionalProperties":false,"maxProperties":1,"properties":{"systemimage:channels":{"type":"null"},"asteroid_os:channels":{"type":"null"}}},"value":{"description":"Default value of the option"},"values":{"title":"Values","type":"array","description":"List of values for the select."}},"required":["var","name","type"]}},"prerequisites":{"title":"Prerequisites","type":"array","description":"An array of strings referring to user_actions defined above that are needed before the installation. This should not include the steps from the generic unlock block, but actions specific to the installation of this operating system.","items":{"type":"string","description":"Reference to user_action that's needed before the installation of this OS. Steps required for every OS should be put in the generic unlock block instead."}},"steps":{"title":"Steps","type":"array","description":"An ordered array of objects describing steps required to install the operating system.","items":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/step.schema.yml","title":"Step","type":"object","description":"Installation step.","properties":{"actions":{"title":"group step","type":"array","items":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/action.schema.yml","title":"Action","type":"object","description":"Atomic action","oneOf":[{"title":"heimdall:flash action","required":["heimdall:flash"],"properties":{"heimdall:flash":{"title":"heimdall:flash action","type":"object","properties":{"partitions":{"title":"Partitions","type":"array","description":"Partitions to flash","items":{"title":"Partition","type":"object","description":"Partition to flash","properties":{"partition":{"title":"Partition","type":"string"},"file":{"title":"File","type":"string"},"group":{"title":"Group","type":"string"}}}}},"additionalProperties":false}}},{"title":"core:info action","required":["core:info"],"properties":{"core:info":{"title":"core:info action","type":"object","properties":{"status":{"title":"Status message","type":"string","description":"Message displayed in the upper line of the footer"},"dots":{"title":"Dots (waiting animation)","type":"boolean","description":"Dots (waiting animation) in the upper line of the footer"},"info":{"title":"Info message","type":"string","description":"Message displayed in the lower line of the footer"},"progress":{"title":"Progress","type":"number","description":"Progress bar (omit to hide)","minimum":0,"maximum":1},"speed":{"title":"Speed","type":"number","description":"speed in MB/s (omit to hide)","minimum":0,"maximum":5000}}}}},{"title":"core:group action","required":["core:group"],"properties":{"core:group":{"title":"core:group action","type":"array","items":{"$ref":"#/properties/operating_systems/items/properties/steps/items"}}}},{"title":"core:user_action action","required":["core:user_action"],"properties":{"core:user_action":{"title":"core:user_action action","type":"object","properties":{"action":{"title":"User action","type":"string","description":"user action to run"}},"required":["action"],"additionalProperties":false}}},{"title":"fastboot:oem_unlock action","required":["fastboot:oem_unlock"],"properties":{"fastboot:oem_unlock":{"title":"fastboot:oem_unlock action","oneOf":[{"type":"null"},{"type":"object","properties":{"code_url":{"title":"Code url","type":"string","description":"Website to obtain an unlock code"}},"additionalProperties":false}]}}},{"title":"fastboot:flashing_unlock action","required":["fastboot:flashing_unlock"],"properties":{"fastboot:flashing_unlock":{"title":"fastboot:flashing_unlock action","type":"null"}}},{"title":"fastboot:reboot_bootloader action","required":["fastboot:reboot_bootloader"],"properties":{"fastboot:reboot_bootloader":{"title":"fastboot:reboot_bootloader action","type":"null"}}},{"title":"fastboot:update action","required":["fastboot:update"],"properties":{"fastboot:update":{"title":"fastboot:update action","type":"object","additionalProperties":false}}},{"title":"systemimage:install action","required":["systemimage:install"],"properties":{"systemimage:install":{"title":"systemimage:install action","type":"null"}}},{"title":"asteroid_os:download action","required":["asteroid_os:download"],"properties":{"asteroid_os:download":{"title":"asteroid_os:download action","type":"null"}}},{"title":"fastboot:boot action","required":["fastboot:boot"],"properties":{"fastboot:boot":{"title":"fastboot:boot action","type":"object","properties":{"file":{"title":"File","type":"string"},"group":{"title":"Group","type":"string"}},"additionalProperties":false}}},{"title":"fastboot:reboot action","required":["fastboot:reboot"],"properties":{"fastboot:reboot":{"title":"fastboot:reboot action","type":"null"}}},{"title":"fastboot:continue action","required":["fastboot:continue"],"properties":{"fastboot:continue":{"title":"fastboot:continue action","type":"null"}}},{"title":"fastboot:erase action","required":["fastboot:erase"],"properties":{"fastboot:erase":{"title":"fastboot:erase action","type":"object","properties":{"partition":{"title":"Partition","type":"string","description":"Partition to format."}},"additionalProperties":false}}},{"title":"fastboot:format action","required":["fastboot:format"],"properties":{"fastboot:format":{"title":"fastboot:format action","type":"object","properties":{"partition":{"title":"Partition","type":"string","description":"Partition to format."},"type":{"title":"Partition type","type":"string","description":"Partition type to use","enum":["ext2","ext4"]},"size":{"title":"Partition size","type":"number","description":"Partition size"}},"additionalProperties":false}}},{"title":"fastboot:flash action","required":["fastboot:flash"],"properties":{"fastboot:flash":{"title":"fastboot:flash action","type":"object","properties":{"partitions":{"title":"Partitions","type":"array","description":"Partitions to flash","items":{"title":"Partition","type":"object","description":"Partition to flash","properties":{"partition":{"title":"Partition","type":"string"},"file":{"title":"File","type":"string"},"group":{"title":"Group","type":"string"}}}}},"additionalProperties":false}}},{"title":"fastboot:set_active action","required":["fastboot:set_active"],"properties":{"fastboot:set_active":{"title":"fastboot:set_active action","type":"object","properties":{"slot":{"title":"To state","type":"string","enum":["a","b"]}},"additionalProperties":false}}},{"title":"adb:shell action","required":["adb:shell"],"properties":{"adb:reboot":{"title":"adb:shell action","type":"object","description":"Run a command on the device via adb shell","properties":{"args":{"title":"Arguments","type":"array","description":"Shell arguments","items":{"type":"string"}}},"required":["args"],"additionalProperties":false}}},{"title":"adb:reboot action","required":["adb:reboot"],"properties":{"adb:reboot":{"title":"adb:reboot action","type":"object","properties":{"to_state":{"title":"To state","type":"string","description":"State to rebot to.","enum":["recovery","system","bootloader"]}},"required":["to_state"],"additionalProperties":false}}},{"title":"adb:format action","required":["adb:format"],"properties":{"adb:format":{"title":"adb:format action","type":"object","properties":{"partition":{"title":"Partition","type":"string","description":"Partition to format."}},"additionalProperties":false}}},{"title":"adb:sideload action","required":["adb:sideload"],"properties":{"adb:sideload":{"title":"adb:sideload action","type":"object","properties":{"file":{"title":"Zip to sideload","type":"string"},"group":{"title":"Group","type":"string"}},"required":["file","group"],"additionalProperties":false}}},{"title":"adb:push action","required":["adb:push"],"properties":{"adb:push":{"title":"adb:push action","type":"object","properties":{"files":{"title":"Files","description":"File names to push","type":"array","items":{"type":"string"}},"group":{"title":"Group","type":"string"},"dest":{"title":"Destination path","description":"Path on the device to push files to","type":"string"}},"required":["file","group"],"additionalProperties":false}}},{"title":"adb:preparesystemimage action","required":["adb:preparesystemimage"],"properties":{"adb:preparesystemimage":{"type":"null"}},"additionalProperties":false},{"title":"core:download action","required":["core:download"],"properties":{"core:download":{"title":"core:download action","type":"object","properties":{"group":{"title":"Group","type":"string","description":"Files group"},"files":{"title":"Files","type":"array","description":"Array of files to download.","items":{"title":"File","type":"object","properties":{"url":{"type":"string","description":"URL of the file to download"},"name":{"type":"string","description":"Name to save the file under on disk"},"checksum":{"$ref":"#/properties/handlers/properties/bootloader_locked/properties/actions/items/oneOf/26/properties/core%3Amanual_download/properties/file/properties/checksum"}},"required":["url"],"additionalProperties":false}}},"required":["group","files"],"additionalProperties":false}}},{"title":"core:write action","required":["core:write"],"properties":{"core:write":{"title":"core:write action","type":"object","properties":{"group":{"title":"Group","type":"string"},"file":{"title":"File","type":"string"},"content":{"title":"Content","type":"string"}},"additionalProperties":false}}},{"title":"core:unpack action","required":["core:unpack"],"properties":{"core:unpack":{"title":"core:unpack action","type":"object","properties":{"group":{"title":"Group","type":"string"},"files":{"type":"array","items":{"type":"object","properties":{"archive":{"title":"Zip to sideload","type":"string"},"dir":{"title":"Target directory","type":"string"}}}}},"additionalProperties":false}}},{"title":"core:manual_download action","required":["core:manual_download"],"properties":{"core:manual_download":{"title":"core:manual_download action","type":"object","properties":{"group":{"title":"Group","type":"string","description":"Files group"},"file":{"title":"File","type":"object","description":"File to download","properties":{"url":{"type":"string","description":"URL of the file to download"},"checksum":{"$schema":"http://json-schema.org/draft-07/schema#","$id":"v3/schema/checksum.schema.yml","title":"Checksum","type":"object","description":"Verify a file's integrity by checking it with a hashing algorithm","properties":{"sum":{"title":"Hash","type":"string","description":"Checksum of the file to download"},"algorithm":{"title":"Hashing algorithm","type":"string","description":"Hashing algorithm to use to calculate the checksum","enum":["RSA-MD4","RSA-MD5","RSA-MDC2","RSA-RIPEMD160","RSA-SHA1","RSA-SHA1-2","RSA-SHA224","RSA-SHA256","RSA-SHA3-224","RSA-SHA3-256","RSA-SHA3-384","RSA-SHA3-512","RSA-SHA384","RSA-SHA512","RSA-SHA512/224","RSA-SHA512/256","RSA-SM3","blake2b512","blake2s256","id-rsassa-pkcs1-v1_5-with-sha3-224","id-rsassa-pkcs1-v1_5-with-sha3-256","id-rsassa-pkcs1-v1_5-with-sha3-384","id-rsassa-pkcs1-v1_5-with-sha3-512","md4","md4WithRSAEncryption","md5","md5-sha1","md5WithRSAEncryption","mdc2","mdc2WithRSA","ripemd","ripemd160","ripemd160WithRSA","rmd160","sha1","sha1WithRSAEncryption","sha224","sha224WithRSAEncryption","sha256","sha256WithRSAEncryption","sha3-224","sha3-256","sha3-384","sha3-512","sha384","sha384WithRSAEncryption","sha512","sha512-224","sha512-224WithRSAEncryption","sha512-256","sha512-256WithRSAEncryption","sha512WithRSAEncryption","shake128","shake256","sm3","sm3WithRSAEncryption","ssl3-md5","ssl3-sha1","whirlpool"]}}}}}},"additionalProperties":false}}}]}},"fallback":{"title":"Fallback steps","type":"array","items":{"$ref":"#/properties/handlers/properties/bootloader_locked/properties/actions/items"}},"optional":{"type":"boolean","description":"If true, errors in this step will be ignored"},"condition":{"title":"Condition","description":"Query an installation option to determine if the step should be run","$ref":"#/properties/handlers/properties/bootloader_locked/properties/actions/items/oneOf/2/properties/core%3Agroup/items/properties/condition/oneOf/1/properties/OR/items"}},"additionalProperties":false}},"eula":{"title":"EULA","type":"object","description":"An end-user license agreement"},"slideshow":{"title":"Slideshow","type":"array","description":"An array of slides presenting the operating system's most compelling features.","items":{"title":"Slide","type":"object","description":"Slide about the operating system","properties":{"title":{"title":"Slide title","type":"string","description":"Title of the slide"},"text":{"title":"Slide text","type":"string","description":"Text body of the slide, Markdown supported here."},"image":{"title":"Slide image","type":"string","description":"Image displayed on the slide."}}}},"video":{"type":"string","description":"A video introducing the user to the operating system they just installed."},"donate":{"type":"string","description":"A link to donate to the developer of the operating system."},"get_involved":{"type":"string","description":"A link to the OSs get involved page."}},"additionalProperties":false}}},"required":["name","codename","operating_systems","formfactor"],"additionalProperties":false}

=== rubencarneiro/sagetea.github.io/installer-configs/v2/devices/sargo.json
{"name":"XFONE","codename":"sargo","formfactor":"phone","aliases":[],"doppelgangers":[],"user_actions":{"bootloader":{"title":"Reboot to Bootloader","description":"With the device powered off, press and hold the volume down and power buttons until the screen turns on. It should say 'Fastboot Mode' underneath the warning sign.","image":"phone_power_down","button":true},"recovery":{"title":"Reboot to Recovery","description":"With the device still at the 'Fastboot Mode' screen (if not, power off the device and press and hold volume down and power buttons until the screen turns on), select the 'Recovery Mode' option by using the volume buttons and press the power button to enter.","image":"phone_power_down","button":true},"downgrade_android":{"title":"Downgrade Android","description":"If the device is running an Android version above 9.0, you have to downgrade to the last 9.0 release. Please make sure to flash version PQ3B.190801.002 of the factory image before proceeding.","link":"https://developers.google.com/android/images#sargo"},"support":{"title":"Support","description":"For details about Supporting Ubuntu Touch development.","link":"https://ubports.com/pt/join-us"}},"unlock":["downgrade_android","support"],"handlers":{"bootloader_locked":{"actions":[{"fastboot:flashing_unlock":null}]}},"operating_systems":[{"name":"Ubuntu Touch","options":[{"var":"channel","name":"Channel","tooltip":"The release channel","link":"https://docs.ubports.com/en/latest/about/process/release-schedule.html","type":"select","remote_values":{"systemimage:channels":null}},{"var":"wipe","name":"Wipe Userdata","tooltip":"Wipe personal data","type":"checkbox"},{"var":"bootstrap","name":"Bootstrap","tooltip":"Flash system partitions using fastboot","type":"checkbox","value":true}],"prerequisites":[],"steps":[{"actions":[{"core:download":{"group":"firmware","files":[{"url":"https://system-image.sageteamobile.com/images/sargo/boot.img","checksum":{"sum":"8feab953fe368d370db772844543eec01a1a4dc5fc0ea469c82be7ba22375f6b","algorithm":"sha256"}},{"url":"https://system-image.sageteamobile.com/images/sargo/dtbo.img","checksum":{"sum":"51e63686ee4bb15e1ddc296f8809996d645d114347daebacc561cf02d2bfce2d","algorithm":"sha256"}},{"url":"https://system-image.sageteamobile.com/images/sargo/vbmeta.img","checksum":{"sum":"854a2c2a5e82c2c49a5d9d62c70334002c7dcd9203f904952ff5fc43b2eac420","algorithm":"sha256"}}]}}],"condition":{"var":"bootstrap","value":true}},{"actions":[{"adb:reboot":{"to_state":"bootloader"}}],"fallback":[{"core:user_action":{"action":"bootloader"}}],"condition":{"var":"bootstrap","value":true}},{"actions":[{"fastboot:flash":{"partitions":[{"partition":"boot","file":"boot.img","group":"firmware"},{"partition":"dtbo","file":"dtbo.img","group":"firmware"},{"partition":"vbmeta","file":"vbmeta.img","group":"firmware","flags":["--disable-verity","--disable-verification"]}]}}],"condition":{"var":"bootstrap","value":true}},{"actions":[{"fastboot:format":{"partition":"userdata","type":"ext4"}}],"condition":{"var":"wipe","value":true}},{"actions":[{"core:user_action":{"action":"recovery"}}],"condition":{"var":"bootstrap","value":true}},{"actions":[{"adb:reboot":{"to_state":"recovery"}}],"fallback":[{"core:user_action":{"action":"recovery"}}],"condition":{"var":"bootstrap","value":false}},{"actions":[{"systemimage:install":null}]},{"actions":[{"adb:reboot":{"to_state":"recovery"}}],"fallback":[{"core:user_action":{"action":"recovery"}}]}],"slideshow":[]}]}
